name: Build cloudflared

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up FreeBSD VM
      uses: vmactions/freebsd-vm@v1.0.8
      with:
        usesh: true
        version: '14.0'
        prepare: |
          pkg install -y node wget curl git go1.22.2 gcc bash gawk gsed
          ln -s /usr/local/bin/go1.22.2 /usr/local/bin/go
        run: |
           git clone https://github.com/cloudflare/cloudflared
           make cloudflared

    - name: Upload cloudflared binary
      uses: actions/upload-artifact@v4
      with:
        name: cloudflared
        path: cloudflared/cloudflared
