name: Build cloudflared

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up FreeBSD VM
      uses: vmactions/freebsd-vm@v1.0.8
      with:
        version: '14.0'  # You can指定 FreeBSD的版本

    - name: Install dependencies
      run: |
        pkg install -y node wget curl git make gcc bash gawk gsed

    - name: Clone cloudflared repository
      run: |
        git clone https://github.com/cloudflare/cloudflared
        cd cloudflared
        ./.teamcity/install-cloudflare-go.sh

    - name: Set up Go environment
      run: |
        echo 'export GOPATH=$HOME/go' >> ~/.profile
        echo 'export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH' >> ~/.profile
        source ~/.profile
        go version

    - name: Build cloudflared
      run: |
        source ~/.profile
        cd cloudflared
        PATH="/tmp/go/bin:$PATH" make cloudflared

    - name: Upload cloudflared binary
      uses: actions/upload-artifact@v2
      with:
        name: cloudflared
        path: cloudflared/cloudflared
