60u&L5@3Iacu!5bFWR3c

name: Build cloudflared

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up FreeBSD VM
      uses: vmactions/freebsd-vm@v1.0.8
      with:
        usesh: true
        version: '13.2'
        prepare: |
          pkg install -y node wget curl git go1.22.2 gcc bash gawk gsed golang-go
          ln -s /usr/local/bin/go1.22.2 /usr/local/bin/go
        run: |
           go get -v github.com/cloudflare/cloudflared/cmd/cloudflared
           GOOS=freebsd GOARCH=amd64 go build -v -x github.com/cloudflare/cloudflared/cmd/cloudflared

    - name: Upload cloudflared binary
      uses: actions/upload-artifact@v4
      with:
        name: cloudflared
        path: cloudflared/cloudflared
